default:
  image: "zevrant/gitlab-runner:latest"

#job:
#  only:
#    - master@github.com/zevrant/zevrant-home-ui
#  extends:
#  when: delayed
#  start_in:
#  rules:
#    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
#      when: always


before_script:
  - VERSION=`aws ssm get-parameter --name zevrant-home-ui-VERSION`
  - VERSION=` echo $VERSION | jq .Parameter.Value`;
  - chrlen=`expr ${#VERSION} - 1`
  - VERSION=`echo $VERSION | cut -c2-$chrlen`
  - echo $VERSION

stages:
  - test
  - imageBuild
  - deploy
  - updateVersion

test:
  stage: test
  script: bash gradlew test sonar --info

imageBuild:
  stage: imageBuild
  script:
    - bash gradlew assemble -PprojVersion=$VERSION
    - "docker build --build-arg a_version=$VERSION -t zevrant/zevrant-home-ui:latest -t zevrant/zevrant-home-ui:$VERSION ."
    - "docker push zevrant/zevrant-home-ui:latest"
    - "docker push zevrant/zevrant-home-ui:$VERSION; docker push zevrant/zevrant-home-ui:latest"
updateVersion:
  stage: updateVersion
  script:
    - 'git tag zevrant-home-ui-$VERSION'
    - export VERSION_BACK="$VERSION"
    - IFS='.'
    - read -ra arr <<< "$VERSION"
    - minorVersion=$( expr ${arr[2]} + 1 )
    - echo $minorVersion
    - aws ssm put-parameter --name zevrant-home-ui-VERSION --value ${arr[0]}.${arr[1]}.$minorVersion --type String --overwrite

deploy:
  stage: deploy
  script:
    - VERSION=$VERSION AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID docker stack deploy --compose-file docker-compose.yml zevrant-home-ui
