default:
  image: "zevrant/gitlab-runner:latest"

#job:
#  only:
#    - master@github.com/zevrant/zevrant-home-ui
#  extends:
#  when: delayed
#  start_in:
#  rules:
#    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
#      when: always


before_script:
  - VERSION=`aws ssm get-parameter --name zevrant-home-ui-VERSION`
  - VERSION=` echo $VERSION | jq .Parameter.Value`;
  - chrlen=`expr ${#VERSION} - 1`
  - VERSION=`echo $VERSION | cut -c2-$chrlen`
  - echo $VERSION

stages:
  - test
  - sonarScan
  - updateVersion
  - imageBuild
  - deploy


sonarScan:
  stage: sonarScan
  script: bash gradlew sonar

test:
  stage: test
  script: bash gradlew test

imageBuild:
  stage: imageBuild
  script:
    - 'bash gradlew assemble -PprojVersion=$VERSION'
    - 'buildx build --platform linux/amd64,linux/arm64,linux/arm/v7  --build-arg a_version=$VERSION -t zevrant/zevrant-home-ui:latest -t zevrant/zevrant-home-ui:$VERSION .'
    - 'docker push zevrant/zevrant-home-ui:latest'
    - 'docker push zevrant/zevrant-home-ui:$VERSION'
    - 'git tag zevrant-home-ui-$VERSION'

updateVersion:
  stage: updateVersion
  script:
    - IFS='.'
    - read -ra arr <<< "$VERSION"
    - minorVersion=$( expr ${arr[2]} + 1 )
    - aws ssm put-parameter --name zevrant-home-ui-VERSION --value ${arr[0]}.${arr[1]}.$minorVersion --type String --overwrite

deploy:
  stage: deploy
  script:
    - VERSION=$VERSION docker stack deploy --resolve-image=never --compose-file docker-compose.yml zevrant-home-ui
