apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-home-ui-deployment
  labels:
    app: zevrant-home-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zevrant-home-ui
  template:
    metadata:
      labels:
        app: zevrant-home-ui
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        architecture: amd64
      containers:
        - name: zevrant-home-ui
          image: zevrant/zevrant-home-ui:$VERSION
          env:
            - name: ENVIRONMENT
              value: $ENVIRONMENT
          ports:
            - containerPort: 9001
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-home-ui/actuator/health
              port: 8080
            initialDelaySeconds: 10
