apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: zevrant-home-ui-controller
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - zevrant-home-ui
  template:
    metadata:
      labels:
        app: zevrant-home-ui
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: zevrant-home-ui
          image: zevrant/zevrant-home-ui:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-key
                  key: aws-secret-key
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-home-ui/actuator/health
              port: 8080
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-home-ui/actuator/health
              port: 8080
            initialDelaySeconds: 10
