spring:
  application:
    name: zevrant-home-ui

server:
  servlet:
    context-path: /${spring.application.name}
  port: 8000

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8999/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    ldap:
      enabled: false

