spring:
  application:
    name: zevrant-home-ui

server:
  servlet:
    context-path: /${spring.application.name}
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:7644/eureka/

zuul:
  routes:
    all:
      path: /zevrant-oauth2-service/**
      url: http://localhost:7644/zevrant-oauth2-service/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    ldap:
      enabled: false


