spring:
  application:
    name: zevrant-home-ui

server:
  servlet:
    context-path: /${spring.application.name}
  port: 8000

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8999/eureka/

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 200
    max-per-route-connections: 20
    time-unit: MILLISECONDS
    time-to-live: 10000
  routes:
    oauth:
      path: /zevrant-oauth2-service/**
      service-id: ZEVRANT-OAUTH2-SERVICE
      stripPrefix: false
    discovery:
      path: /zevrant-discovery-service/**
      stripPrefix: false
      url: http://127.0.0.1:8999:8999

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    ldap:
      enabled: false

ribbon:
  eureka:
    enable: true
  isSecure: false
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
        semaphore:
          maxConcurrentRequests: 100000 # basically 'unlimited'
        timeout:
          enabled: false
      circuitBreaker:
        enabled: false
      fallback:
        enabled: false
