eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:7446/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${IP_ADDRESS}
    ip-address: ${IP_ADDRESS}

server:
  ssl:
    key-store: /storage/keys/zevrant-services.p12
    key-store-type: PKCS12
    key-store-password: ${ssl.keystore.password}

zevrant:
  encrypted:
    properties: ssl/keystore/password

context:
  initializer:
    classes: net.zevrant.services.security.common.secrets.management.services.EncryptedPropertyContextInitializer
