eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.238.10:8999/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${IP_ADDRESS}
    ip-address: ${IP_ADDRESS}

zuul:
  routes:
    all:
      path: /zevrant-oauth2-service/**
      url: https://zevrant-service.com:8000/zevrant-oauth2-service/
