server:
  servlet:
    context-path: /zevrant-home-ui

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: http://zevrant-services.net:8000/zevrant-discovery-service
