spring:
  application:
    name: zevrant-home-ui

server:
  servlet:
    context-path: /${spring.application.name}
  port: 8000

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8999/eureka/

zuul:
  routes:
    oauth:
      path: /zevrant-oauth2-service/**
      service-id: ZEVRANT-OAUTH2-SERVICE
      stripPrefix: false
    discovery:
      path: /zevrant-discovery-service/**
      stripPrefix: false
      url: http://127.0.0.1:8999:8999

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    ldap:
      enabled: false

ribbon:
  eureka:
    enabled: true
  eager-load:
    clients: true



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000000
