spring:
  application:
    name: zevrant-home-ui
  servlet:
    multipart:
      max-request-size: 999999999999999999
      max-file-size: 999999999999999999

server:
  tomcat:
    max-threads: 1
  servlet:
    context-path: /${spring.application.name}
  port: 7644
  max-http-header-size: 99999999999

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8999/eureka/

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 200
    max-per-route-connections: 20
    time-unit: MILLISECONDS
    time-to-live: 10000
  routes:
    model:
      sensitiveHeaders:
      path: /zevrant-model-service/**
      service-id: ZEVRANT-MODEL-SERVICE
      stripPrefix: false
    oauth:
      sensitiveHeaders:
      path: /zevrant-oauth2-service/**
      service-id: ZEVRANT-OAUTH2-SERVICE
      stripPrefix: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    ldap:
      enabled: false

ribbon:
  eureka:
    enable: true
  isSecure: false
  ReadTimeout: 60000
  ConnectTimeout: 60000

