spring:
  application:
    name: zevrant-home-ui

server:
  servlet:
    context-path: /${spring.application.name}
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:7446/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    ldap:
      enabled: false
