server:
  servlet:
    context-path: /${spring.application.name}


zuul:
  routes:
    model:
      sensitiveHeaders:
      path: /zevrant-model-service/**
      url: https://zevrant-model-service
      stripPrefix: false
    oauth:
      sensitiveHeaders:
      path: /zevrant-oauth2-service/**
      url: https://zevrant-oauth2-service
      stripPrefix: false
    outsource:
      sensitiveHeaders:
      path: /zevrant-outsource-service/**
      url: https://zevrant-outsource-service
      stripPrefix: false
