spring:
  application:
    name: zevrant-home-ui

server:
  servlet:
    context-path: /${spring.application.name}
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true

zuul:
  routes:
    all:
      path: /zevrant-oauth2-service/**
      url: http://localhost:7644/zevrant-oauth2-service/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    ldap:
      enabled: false


