spring:
  webflux:
    base-path: /
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    ldap:
      enabled: false

logging:
  level:
    root: info
    com:
      zevrant:
        services:
          zevranthomeui: debug


